In [2]:
import os
import re
import gc
import glob
import pickle
import warnings
import os.path
import itertools
import numpy as np
import pandas as pd
import pandas.io.common

from tqdm import tqdm
from datetime import datetime
warnings.filterwarnings("ignore")

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

## READING Data Sources Features

In [51]:
## Anomaly Data (Baseline data)
loc_path = r'/Users/raj2.gaurav/Desktop/' 
anomaly_features_path = loc_path + 'Causal Model/04. Feature Store/01. Anomaly Features/'
anomaly_df = pd.read_parquet(anomaly_features_path + 'Anomaly_features.parquet')
anomaly_df_br=anomaly_df[anomaly_df['Circle']=='bihar']

In [13]:
## LSR Feature 
lsr_features_path = loc_path + 'Causal Model/04. Feature Store/02. LSR Features/'
lsr_df = pd.read_parquet(lsr_features_path + 'Lsr_features.parquet')

In [17]:
## Network Health Feature
ccl_features_path = loc_path + 'Causal Model/04. Feature Store/03. Nework Health Features/'
ccl_df = pd.read_parquet(ccl_features_path + 'Netowork_features.parquet')

In [18]:
## PRB Feature
prb_features_path = loc_path + 'Causal Model/04. Feature Store/04. PRB Features/'
prb_df = pd.read_parquet(prb_features_path + 'Prb_features.parquet')

In [52]:
anomaly_df_br.head()

,Circle,City,Component,Partition_date,Hour,Total customers,Anomaly,Ratio data,Ratio voice,Ratio hsi,Cluster_issue,Data volume,Data volume formula,Data volume mean,Data volume std,Voice affected users,Voice affected users formula,Voice affected users mean,Voice affected users std,Hsi affected users,Hsi affected users formula,Hsi affected users mean,Hsi affected users std,Num_grids,Num_cells,Num_sectors,Indoor frqeqency % 850,Indoor frqeqency % 1800,Indoor frqeqency % 2300,Prb_10,Prb_10_25,Prb_25_70,Prb_70_90,Prb_90,Target_Cluster
4,bihar,patna,75,2022-11-01,11,20370,Data - Voice,7,8,2,high_indoor_sessions,328,160,42,39,3154,1401,354,348,689,1214,288,308,23,111,34,29,35,35,3.00,10.00,86.00,12.00,0.00,1
5,bihar,patna,75,2022-11-01,12,20236,Data - Voice,7,9,2,high_indoor_sessions,322,162,42,40,3093,1368,339,343,662,1242,295,315,23,111,34,28,37,34,4.00,13.00,79.00,14.00,1.00,1
7,bihar,patna,75,2022-11-01,10,21623,Data - Voice,7,8,1,high_indoor_sessions,317,152,41,37,2909,1367,355,337,513,1311,323,329,23,111,34,29,37,33,4.00,11.00,82.00,13.00,1.00,1
9,bihar,patna,75,2022-11-01,13,19342,Data - Voice,7,8,2,high_indoor_sessions,283,144,37,35,2815,1244,312,310,727,1206,282,308,23,111,34,28,36,34,3.00,9.00,82.00,16.00,1.00,1
11,bihar,patna,75,2022-11-01,15,19364,Data - Voice,8,8,3,high_indoor_sessions,292,147,36,36,2738,1208,307,300,710,971,202,256,23,111,34,29,36,34,3.00,12.00,85.00,7.00,4.00,1

In [54]:
anomaly_df_br.shape

(42634, 35)

In [21]:
lsr_df.head()

,Circle,City,Partition_date,Component,Hour,Sum_total_volume_mb_download,Sum_total_volume_mb_upload,Unique_customers,Total_duration_sec,Total_sessions,Rsrp_nom,Rsrp_dnom,Rsrq_nom,Rsrq_dnom,Mean_cqi_nom,Mean_cqi_dnom,Pusch_sinr_nom,Pusch_sinr_dnom,Ta_distance_nom,Ta_distance_dnom,Intersite_distance_nom,Intersite_distance_dnom,Rsrp_nom_lag_1_day,Rsrp_dnom_lag_1_day,Rsrq_nom_lag_1_day,Rsrq_dnom_lag_1_day
275585,bihar,bagaha,2022-11-03,50,3,979962576.00,41459135.00,301,68040,3016,-154641.00,1525,-16045.00,1525,30920.00,3003,39813.70,2839,3584212.00,3016,6252803.00,3016,-154641.00,1525.00,-16045.00,1525.00
183716,bihar,jamshedpur,2022-11-03,114,21,164019253862.00,18363790274.00,9237,4759403,116366,-8589648.00,93517,-1339488.50,93517,924133.00,115784,771762.40,57458,26652000.00,116366,38538303.00,116366,-8589648.00,93517.00,-1339488.50,93517.00
183717,bihar,bokaro_steel_city,2022-11-03,123,21,59475807199.00,5055020583.00,2882,1465781,26667,-1643720.00,17635,-248222.50,17635,234934.00,26514,236453.10,16151,9583052.00,26667,19986012.00,26667,-1643720.00,17635.00,-248222.50,17635.00
183718,bihar,chirkunda,2022-11-03,44,21,24801019147.00,1401710779.00,1050,620816,10419,-622451.00,5797,-79287.00,5797,89335.00,10341,69489.10,7968,14705718.00,10419,17250691.00,10419,-622451.00,5797.00,-79287.00,5797.00
183719,bihar,lakhisarai,2022-11-03,17,21,61738316591.00,5008062642.00,3670,1586822,36777,-2925510.00,30966,-445793.50,30966,277519.00,36585,264499.60,21778,18127887.00,36777,29238084.00,36777,-2925510.00,30966.00,-445793.50,30966.00

In [57]:
anomaly_df_br.dtypes

Circle                           object
City                             object
Component                         int64
Partition_date                   object
Hour                              int64
Total customers                   int64
Anomaly                          object
Ratio data                        int64
Ratio voice                       int64
Ratio hsi                         int64
Cluster_issue                    object
Data volume                       int64
Data volume formula               int64
Data volume mean                  int64
Data volume std                   int64
Voice affected users              int64
Voice affected users formula      int64
Voice affected users mean         int64
Voice affected users std          int64
Hsi affected users                int64
Hsi affected users formula        int64
Hsi affected users mean           int64
Hsi affected users std            int64
Num_grids                         int64
Num_cells                         int64
Num_sectors                       int64
Indoor frqeqency % 850            int64
Indoor frqeqency % 1800           int64
Indoor frqeqency % 2300           int64
Prb_10                          float64
Prb_10_25                       float64
Prb_25_70                       float64
Prb_70_90                       float64
Prb_90                          float64
Target_Cluster                    int64
dtype: object

In [58]:
lsr_df.dtypes

Circle                           object
City                             object
Partition_date                   object
Component                         int64
Hour                              int32
Sum_total_volume_mb_download     object
Sum_total_volume_mb_upload       object
Unique_customers                  int64
Total_duration_sec                int64
Total_sessions                    int64
Rsrp_nom                         object
Rsrp_dnom                         int64
Rsrq_nom                         object
Rsrq_dnom                         int64
Mean_cqi_nom                    float64
Mean_cqi_dnom                     int64
Pusch_sinr_nom                   object
Pusch_sinr_dnom                   int64
Ta_distance_nom                  object
Ta_distance_dnom                  int64
Intersite_distance_nom           object
Intersite_distance_dnom           int64
Rsrp_nom_lag_1_day               object
Rsrp_dnom_lag_1_day             float64
Rsrq_nom_lag_1_day               object
Rsrq_dnom_lag_1_day             float64
dtype: object

In [ ]:
## Joining with Lsr Data

In [55]:
anomaly_lsr_df=pd.merge(anomaly_df_br,lsr_df,on=['Circle','City','Partition_date','Component','Hour'],how='left')

In [56]:
anomaly_lsr_df.head()

,Circle,City,Component,Partition_date,Hour,Total customers,Anomaly,Ratio data,Ratio voice,Ratio hsi,Cluster_issue,Data volume,Data volume formula,Data volume mean,Data volume std,Voice affected users,Voice affected users formula,Voice affected users mean,Voice affected users std,Hsi affected users,Hsi affected users formula,Hsi affected users mean,Hsi affected users std,Num_grids,Num_cells,Num_sectors,Indoor frqeqency % 850,Indoor frqeqency % 1800,Indoor frqeqency % 2300,Prb_10,Prb_10_25,Prb_25_70,Prb_70_90,Prb_90,Target_Cluster,Sum_total_volume_mb_download,Sum_total_volume_mb_upload,Unique_customers,Total_duration_sec,Total_sessions,Rsrp_nom,Rsrp_dnom,Rsrq_nom,Rsrq_dnom,Mean_cqi_nom,Mean_cqi_dnom,Pusch_sinr_nom,Pusch_sinr_dnom,Ta_distance_nom,Ta_distance_dnom,Intersite_distance_nom,Intersite_distance_dnom,Rsrp_nom_lag_1_day,Rsrp_dnom_lag_1_day,Rsrq_nom_lag_1_day,Rsrq_dnom_lag_1_day
0,bihar,patna,75,2022-11-01,11,20370,Data - Voice,7,8,2,high_indoor_sessions,328,160,42,39,3154,1401,354,348,689,1214,288,308,23,111,34,29,35,35,3.00,10.00,86.00,12.00,0.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bihar,patna,75,2022-11-01,12,20236,Data - Voice,7,9,2,high_indoor_sessions,322,162,42,40,3093,1368,339,343,662,1242,295,315,23,111,34,28,37,34,4.00,13.00,79.00,14.00,1.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bihar,patna,75,2022-11-01,10,21623,Data - Voice,7,8,1,high_indoor_sessions,317,152,41,37,2909,1367,355,337,513,1311,323,329,23,111,34,29,37,33,4.00,11.00,82.00,13.00,1.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bihar,patna,75,2022-11-01,13,19342,Data - Voice,7,8,2,high_indoor_sessions,283,144,37,35,2815,1244,312,310,727,1206,282,308,23,111,34,28,36,34,3.00,9.00,82.00,16.00,1.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bihar,patna,75,2022-11-01,15,19364,Data - Voice,8,8,3,high_indoor_sessions,292,147,36,36,2738,1208,307,300,710,971,202,256,23,111,34,29,36,34,3.00,12.00,85.00,7.00,4.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
## Joining with CCL Data

In [26]:
ccl_df.head()

,Partition_date,Circle,City,Component,Hour,Avg_bad_hsi_pct,Avg_bad_voice_pct
0,2022-11-03,bihar,motihari,151,5,8.05,22.75
1,2022-11-03,bihar,sasaram,1,5,16.77,15.85
2,2022-11-03,bihar,samastipur,72,19,24.92,10.07
3,2022-11-03,bihar,muzaffarpur,54,18,7.68,20.36
4,2022-11-03,bihar,ranchi,122,22,14.59,20.15

In [27]:
ccl_df.shape

(994952, 7)

In [28]:
anomaly_lsr_df.shape

(284614, 56)

In [30]:
ccl_df.dtypes

Partition_date       datetime64[ns]
Circle                       object
City                         object
Component                     Int64
Hour                          Int64
Avg_bad_hsi_pct             float64
Avg_bad_voice_pct           float64
dtype: object

In [31]:
ccl_df['Partition_date']=ccl_df['Partition_date'].astype(str)

In [36]:
anomaly_lsr__ccl_df= pd.merge(anomaly_lsr_df,ccl_df,on=['Circle','City','Partition_date','Component','Hour'],how='left')

In [37]:
anomaly_lsr__ccl_df.head()

,Circle,City,Component,Partition_date,Hour,Total customers,Anomaly,Ratio data,Ratio voice,Ratio hsi,Cluster_issue,Data volume,Data volume formula,Data volume mean,Data volume std,Voice affected users,Voice affected users formula,Voice affected users mean,Voice affected users std,Hsi affected users,Hsi affected users formula,Hsi affected users mean,Hsi affected users std,Num_grids,Num_cells,Num_sectors,Indoor frqeqency % 850,Indoor frqeqency % 1800,Indoor frqeqency % 2300,Prb_10,Prb_10_25,Prb_25_70,Prb_70_90,Prb_90,Target_Cluster,Sum_total_volume_mb_download,Sum_total_volume_mb_upload,Unique_customers,Total_duration_sec,Total_sessions,Rsrp_nom,Rsrp_dnom,Rsrq_nom,Rsrq_dnom,Mean_cqi_nom,Mean_cqi_dnom,Pusch_sinr_nom,Pusch_sinr_dnom,Ta_distance_nom,Ta_distance_dnom,Intersite_distance_nom,Intersite_distance_dnom,Rsrp_nom_lag_1_day,Rsrp_dnom_lag_1_day,Rsrq_nom_lag_1_day,Rsrq_dnom_lag_1_day,Avg_bad_hsi_pct,Avg_bad_voice_pct
0,kolkata,kolkata,1226,2022-11-01,13,44014,Voice - HSI,2,3,5,high_indoor_sessions,358,409,123,95,4236,4074,1127,982,3360,3152,636,838,25,95,30,23,33,42,1.00,8.00,30.00,40.00,15.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,kolkata,kolkata,1226,2022-11-01,12,42214,Voice - HSI,3,3,5,high_indoor_sessions,354,374,110,88,4206,4165,1160,1001,2522,2322,433,629,25,95,30,24,31,43,2.00,11.00,37.00,31.00,14.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,kolkata,kolkata,1226,2022-11-01,11,40135,HSI,3,3,6,high_indoor_sessions,335,358,107,83,4201,4212,1203,1002,2757,2249,423,608,25,95,30,24,32,43,1.00,13.00,44.00,25.00,12.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,karnataka,bangalore,946,2022-11-01,18,24834,Data - Voice - HSI,7,7,10,high_indoor_sessions,402,235,50,61,3205,1748,412,445,2666,1655,264,463,30,117,37,28,29,42,5.00,9.00,59.00,29.00,15.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bihar,patna,75,2022-11-01,11,20370,Data - Voice,7,8,2,high_indoor_sessions,328,160,42,39,3154,1401,354,348,689,1214,288,308,23,111,34,29,35,35,3.00,10.00,86.00,12.00,0.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
prb_df.head()

,Partition_date,City,Component,Hour,Prb_20,Prb_70_90,Prb_90,Ph_mean_prb_dl,Totprbdlmin_perc,Totprbdlmax_perc,Totprbdltot_perc,Totprbdlcnt_cnt
0,2022-11-03,darbhanga,3,19,1,14,15,78.07,29.75,97.83,12541.18,175.80
1,2022-11-03,gaya,15,6,15,1,0,20.54,3.67,63.21,2516.73,175.75
2,2022-11-03,patna,195,5,36,0,0,9.55,2.60,38.91,1236.47,174.19
3,2022-11-03,lakhisarai,24,20,0,5,3,77.74,30.35,96.65,12445.37,175.82
4,2022-11-03,gopalganj,20,11,0,6,4,66.61,19.70,97.13,10485.31,175.79

In [42]:
prb_df['Partition_date'].replace('2023-02-01','2022-11-03',inplace=True)
prb_df['Partition_date'].replace('2023-02-02','2022-11-04',inplace=True)
prb_df['Partition_date'].replace('2023-02-03','2022-11-05',inplace=True)
prb_df['Partition_date'].replace('2023-02-04','2022-11-06',inplace=True)
prb_df['Partition_date'].replace('2023-02-05','2022-11-07',inplace=True)
prb_df['Partition_date'].replace('2023-02-06','2022-11-08',inplace=True)
prb_df['Partition_date'].replace('2023-02-07','2022-11-09',inplace=True)

In [48]:
final_df=pd.merge(anomaly_lsr__ccl_df,ccl_df,on=['Circle','City','Partition_date','Component','Hour'],how='left')

In [49]:
final_df.head()

,Circle,City,Component,Partition_date,Hour,Total customers,Anomaly,Ratio data,Ratio voice,Ratio hsi,Cluster_issue,Data volume,Data volume formula,Data volume mean,Data volume std,Voice affected users,Voice affected users formula,Voice affected users mean,Voice affected users std,Hsi affected users,Hsi affected users formula,Hsi affected users mean,Hsi affected users std,Num_grids,Num_cells,Num_sectors,Indoor frqeqency % 850,Indoor frqeqency % 1800,Indoor frqeqency % 2300,Prb_10,Prb_10_25,Prb_25_70,Prb_70_90,Prb_90,Target_Cluster,Sum_total_volume_mb_download,Sum_total_volume_mb_upload,Unique_customers,Total_duration_sec,Total_sessions,Rsrp_nom,Rsrp_dnom,Rsrq_nom,Rsrq_dnom,Mean_cqi_nom,Mean_cqi_dnom,Pusch_sinr_nom,Pusch_sinr_dnom,Ta_distance_nom,Ta_distance_dnom,Intersite_distance_nom,Intersite_distance_dnom,Rsrp_nom_lag_1_day,Rsrp_dnom_lag_1_day,Rsrq_nom_lag_1_day,Rsrq_dnom_lag_1_day,Avg_bad_hsi_pct_x,Avg_bad_voice_pct_x,Avg_bad_hsi_pct_y,Avg_bad_voice_pct_y
0,kolkata,kolkata,1226,2022-11-01,13,44014,Voice - HSI,2,3,5,high_indoor_sessions,358,409,123,95,4236,4074,1127,982,3360,3152,636,838,25,95,30,23,33,42,1.00,8.00,30.00,40.00,15.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,kolkata,kolkata,1226,2022-11-01,12,42214,Voice - HSI,3,3,5,high_indoor_sessions,354,374,110,88,4206,4165,1160,1001,2522,2322,433,629,25,95,30,24,31,43,2.00,11.00,37.00,31.00,14.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,kolkata,kolkata,1226,2022-11-01,11,40135,HSI,3,3,6,high_indoor_sessions,335,358,107,83,4201,4212,1203,1002,2757,2249,423,608,25,95,30,24,32,43,1.00,13.00,44.00,25.00,12.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,karnataka,bangalore,946,2022-11-01,18,24834,Data - Voice - HSI,7,7,10,high_indoor_sessions,402,235,50,61,3205,1748,412,445,2666,1655,264,463,30,117,37,28,29,42,5.00,9.00,59.00,29.00,15.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bihar,patna,75,2022-11-01,11,20370,Data - Voice,7,8,2,high_indoor_sessions,328,160,42,39,3154,1401,354,348,689,1214,288,308,23,111,34,29,35,35,3.00,10.00,86.00,12.00,0.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
final_df.isnull().sum()

Circle                               0
City                                 0
Component                            0
Partition_date                       0
Hour                                 0
Total customers                      0
Anomaly                              0
Ratio data                           0
Ratio voice                          0
Ratio hsi                            0
Cluster_issue                   140676
Data volume                          0
Data volume formula                  0
Data volume mean                     0
Data volume std                      0
Voice affected users                 0
Voice affected users formula         0
Voice affected users mean            0
Voice affected users std             0
Hsi affected users                   0
Hsi affected users formula           0
Hsi affected users mean              0
Hsi affected users std               0
Num_grids                            0
Num_cells                            0
Num_sectors                          0
Indoor frqeqency % 850               0
Indoor frqeqency % 1800              0
Indoor frqeqency % 2300              0
Prb_10                              39
Prb_10_25                           39
Prb_25_70                           39
Prb_70_90                           39
Prb_90                              39
Target_Cluster                       0
Sum_total_volume_mb_download    263097
Sum_total_volume_mb_upload      263097
Unique_customers                263097
Total_duration_sec              263097
Total_sessions                  263097
Rsrp_nom                        263097
Rsrp_dnom                       263097
Rsrq_nom                        263097
Rsrq_dnom                       263097
Mean_cqi_nom                    263097
Mean_cqi_dnom                   263097
Pusch_sinr_nom                  263110
Pusch_sinr_dnom                 263097
Ta_distance_nom                 263097
Ta_distance_dnom                263097
Intersite_distance_nom          263097
Intersite_distance_dnom         263097
Rsrp_nom_lag_1_day              266806
Rsrp_dnom_lag_1_day             266806
Rsrq_nom_lag_1_day              266806
Rsrq_dnom_lag_1_day             266806
Avg_bad_hsi_pct_x               262982
Avg_bad_voice_pct_x             262272
Avg_bad_hsi_pct_y               262982
Avg_bad_voice_pct_y             262272
dtype: int64